const {spawn}=require('child_process'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/sam/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const proc=spawn('python',['-u','-c',"import launcher;s=launcher.Server(port=0);print(s.origin+'/'+s.token+'/index.html',flush=True);s.serve_forever()"],{cwd:path.resolve(__dirname,'../../MASTER-IT-TOOLKIT')});let browser;
try{const url=await new Promise(resolve=>proc.stdout.once('data',d=>resolve(d.toString().trim())));browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const catalog={tools:{'7zip':{status:'ready',assets:[{platform:'Windows',architecture:'x64'}]},bcu:{status:'manual'},obs:{status:'error'}}};
await page.route('**/api/catalog*',r=>r.fulfill({json:catalog}));await page.route('**/api/workspace',r=>r.fulfill({json:{}}));
await page.goto(url+'#tools');await page.getByLabel('Download method',{exact:true}).waitFor();
await page.evaluate(c=>{window.TOOLKIT_DOWNLOAD_CATALOG=c;window.dispatchEvent(new CustomEvent('toolkit-catalog',{detail:c}));window.dispatchEvent(new CustomEvent('toolkit-inventory',{detail:{tools:{'7zip':{downloaded:true}},host:null}}));},catalog);
const ids=()=>page.locator('[data-select-tool]').evaluateAll(nodes=>nodes.map(n=>n.dataset.selectTool));
await page.getByLabel('Availability',{exact:true}).selectOption('downloaded');assert.deepEqual(await ids(),['7zip']);
await page.getByLabel('Availability',{exact:true}).selectOption('undownloaded');assert(!(await ids()).includes('7zip'));assert((await ids()).includes('bcu'));
await page.getByLabel('Download method',{exact:true}).selectOption('no-auto');assert.deepEqual((await ids()).sort(),['bcu','obs']);
await page.getByLabel('Download method',{exact:true}).selectOption('manual');assert.deepEqual(await ids(),['bcu']);
await page.getByRole('button',{name:'Select all matching (1)',exact:true}).click();assert.equal(await page.locator('[data-select-tool="bcu"]').isChecked(),true);
await page.getByRole('button',{name:'Reset filters',exact:true}).first().click();assert.equal(await page.getByLabel('Download method',{exact:true}).inputValue(),'');
await page.getByLabel('Download method',{exact:true}).selectOption('auto');assert.deepEqual(await ids(),['7zip']);
await page.getByLabel('Tool architecture',{exact:true}).selectOption('arm64');assert.equal((await ids()).length,0);
await page.getByRole('button',{name:'Reset filters',exact:true}).first().click();await page.getByLabel('Tool category',{exact:true}).selectOption('WordPress Development');const wp=await ids();assert(wp.includes('localwp')&&wp.includes('wp-cli'));assert(!wp.includes('7zip'));
await page.getByLabel('Tool license',{exact:true}).selectOption('Open source');assert(!(await ids()).includes('localwp'));assert((await ids()).includes('wp-cli'));
await page.getByRole('button',{name:'Missing downloads',exact:false}).first().click();await page.getByLabel('Priority',{exact:true}).selectOption('P3');const p3=await ids();assert(p3.length>0);const expected=await page.evaluate(()=>window.TOOLKIT_DATA.filter(t=>t.priority==='P3'&&!['Built-in','Documentation','Script'].includes(t.kind)&&t.officialDownload).map(t=>t.id));assert.deepEqual(p3.sort(),expected.sort());
assert.deepEqual(errors,[]);console.log('PASS downloaded/missing independent of host, manual/error/automatic downloads, combined filters, reset, scoped selection, and P3 missing packages.');
}finally{if(browser)await browser.close();proc.kill();}})().catch(e=>{console.error(e);process.exitCode=1});
